// game/render/overlay_ground_gt3gt4.h — PC-native bodies for the A00-overlay GROUND/SCENE
// GT3/GT4 render-packet emitter pair (FUN_8013FB88 = GT3, FUN_8013FE58 = GT4) and their shared
// per-object entity-loop caller (FUN_801401B8). See overlay_ground_gt3gt4.cpp for the full RE
// trace.
//
// WIRED + SBS-gated (frontier, 2026-07-08). Was UNWIRED/UNVERIFIED draft banked ahead of the
// frontier (docs/engine_re.md region-map session); this session re-diffed entityLoop against
// ground truth (generated/ov_a00_shard_0.c ov_a00_gen_801401B8), found + fixed a real bug (a
// spurious extra pointer dereference on the ground-record table — see .cpp), MIRRORED
// entityLoop's own real 40-byte guest-stack frame (was the one honest, explicitly-flagged gap;
// gt3/gt4's frames were already mirrored), and registered all three via ov_a00_set_override.
//
// Sibling of the ALREADY-OWNED (game/render/overlay_gt3gt4.{h,cpp}) FIELD-OBJECT GT3/GT4 emitter
// (FUN_801465EC/801467BC) — docs/engine_re.md ("Deferred render pipeline" + "GAME-STAGE OBJECT
// PIPELINE" step 7) documents these as the OTHER copy: "the ground/scene entities go
// 0x8003D0BC -> 0x801401B8 (entity loop) -> 0x8013FE58/0x8013FB88 (overlay GT4/GT3 submitters)".
// Same shape (GTE RTPT/RTPS + NCLIP + AVSZ3/4-or-custom-blend into the shared packet-pool bump
// allocator + OT linked list), but NOT byte-identical to the field pair — see .cpp for the
// concrete differences (colour mask, byte-packed header counts, 3-way min/max Z-select instead
// of the pairwise-clamp chain).
#pragma once
struct Core;
class  Game;

class OverlayGroundGt3Gt4 {
public:
  static void gt3(Core* c);         // FUN_8013FB88(rec=a0, ot_base=a1, count=a2) -> advanced rec ptr in v0
  static void gt4(Core* c);         // FUN_8013FE58(rec=a0, ot_base=a1, count=a2) -> advanced rec ptr in v0
  static void entityLoop(Core* c);  // FUN_801401B8(list=a0) -> loads camera GTE ctrl regs 0..7 from
                                     // 0x1F8000F8, then walks list's u16 index array calling gt3()/gt4()
                                     // per referenced ground record group.

  // Wired (see file banner): same discipline as OverlayGt3Gt4 — all three are reached by a
  // direct C call generated by the recompiler inside the ov_a00 shard, not rec_dispatch, so
  // wired via the overlay's own `ov_a00_set_override` table (through the process-global
  // override registry's engine_set_override_a00, not a raw table poke).
  static void registerOverrides(Game* game);
};
