// game/render/overlay_gt3gt4.h — PC-native bodies for the A00-overlay GT3/GT4 render-packet
// emitter cluster (FUN_80146478/801465EC/801467BC). See overlay_gt3gt4.cpp for the full RE trace
// and wiring rationale.
//
// This is NOT pc_render (the read-only host-overlay picture pass). This is the SUBSTRATE's own
// GTE + OT + GP0 packet writer — it executes underneath on BOTH SBS cores and its guest-memory
// writes (packet-pool bump-allocator stores, OT bucket link) are part of the byte-exact faithful
// state. The native bodies below reproduce the recompiled MIPS 1:1 (same GTE ops, same guest
// writes, same field layout) — CLAUDE.md's "faithful substrate mirror" carve-out, distinct from
// the render-underneath / pc_render no-guest-write rule that governs game/render/submit.cpp's
// Render::submitPolyGt3Native / submitPolyGt4Native (the MAIN engine's GT3/GT4 path, which is
// deliberately NOT GTE-driven and NOT guest-writing).
#pragma once
struct Core;
class  Game;

class OverlayGt3Gt4 {
public:
  static void gt3(Core* c);   // FUN_801465EC(rec=a0, ot_base=a1, count=a2) -> advanced rec ptr in v0
  static void gt4(Core* c);   // FUN_801467BC(rec=a0, ot_base=a1, count=a2) -> advanced rec ptr in v0

  // Wire both leaf addresses into the ov_a00 overlay's OWN per-shard override table
  // (ov_a00_set_override -> g_ov_a00_override[]), NOT the process-global override registry/
  // rec_dispatch: every caller
  // reaches these two leaves via a direct C call (ov_a00_func_801465EC/801467BC(c)) generated by
  // the recompiler, not a rec_dispatch(addr) indirection — from BOTH FUN_80146478 (the busy
  // render-leaf dispatcher, reached itself via rec_dispatch from the main EXE) and a duplicate
  // tail-shared copy of the same call sequence folded into FUN_80147FC4 by the recompiler's CFG
  // discovery. Overriding the two leaves directly covers every call site uniformly, the same
  // discipline as ActorReward's g_override[] wiring (process-global table; one registration call
  // covers every Core/Game constructed afterward, including SBS's two cores).
  static void registerOverrides(Game* game);
};
