#!/usr/bin/env python3
"""Gate Clang formatting, structure caps, and clang-tidy for a C++ repository."""

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


SCRIPT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CAP = 1200
CRITICAL_LINES = 2000
SOURCE_SUFFIXES = (".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp")
EXCLUDED_TOP_LEVEL = {"build", "external", "generated", "scratch", "vendor"}

# psxport's pre-policy legacy files are frozen at their measured adoption sizes. A cap only moves
# down after an extraction; it never moves up to accommodate growth. Consumer repos use the same
# implementation through --root and declare their own legacy exceptions with --cap.
PSXPORT_CAPS = {
    "runtime/recomp/game_iface.h": 500,
    "runtime/recomp/gpu_native.cpp": 4121,
    "runtime/recomp/gpu_vk.cpp": 4404,
    "runtime/recomp/gpu_vk_semi_selftest.cpp": 200,
    "runtime/recomp/gpu_vk_semi_selftest.h": 40,
    "runtime/recomp/gpu_vk_selftest_support.h": 40,
    "runtime/recomp/gpu_vk_texture_phase_selftest.cpp": 180,
    "runtime/recomp/gpu_vk_texture_phase_selftest.h": 40,
    "runtime/recomp/hle.cpp": 1259,
    "runtime/recomp/interp.cpp": 1242,
    "runtime/recomp/mem.cpp": 1321,
    "runtime/recomp/pc_scheduler.cpp": 661,
    "runtime/recomp/pc_scheduler.h": 177,
    "runtime/recomp/render_queue.cpp": 2547,
    "runtime/recomp/sbs.cpp": 4255,
    "runtime/recomp/synchronous_task_wait.cpp": 220,
    "runtime/recomp/synchronous_task_wait.h": 80,
    "runtime/ui/render_path_control.cpp": 100,
    "runtime/ui/render_path_control.h": 50,
    "tests/test_synchronous_task_wait.cpp": 180,
}


def run_git(root: Path, *args: str) -> list[str]:
    result = subprocess.run(
        ["git", "-C", str(root), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.splitlines()


def is_generated(path: Path) -> bool:
    try:
        prefix = path.read_text(encoding="utf-8", errors="replace")[:512].upper()
    except OSError:
        return False
    return "GENERATED" in prefix and ("DO NOT EDIT" in prefix or "AUTOGENERATED" in prefix)


def source_files(root: Path) -> tuple[list[Path], list[str], list[str]]:
    pathspecs = [f"*{suffix}" for suffix in SOURCE_SUFFIXES]
    listed = set(run_git(root, "ls-files", *pathspecs))
    listed.update(run_git(root, "ls-files", "--others", "--exclude-standard", "--", *pathspecs))
    sources: list[Path] = []
    generated: list[str] = []
    deleted: list[str] = []
    for relative in sorted(listed):
        parts = Path(relative).parts
        if not parts or parts[0] in EXCLUDED_TOP_LEVEL:
            continue
        path = root / relative
        if not path.is_file():
            deleted.append(relative)
            continue
        if is_generated(path):
            generated.append(relative)
            continue
        sources.append(path)
    return sources, generated, deleted


def parse_cap(value: str) -> tuple[str, int]:
    relative, separator, raw_cap = value.rpartition("=")
    if not separator or not relative:
        raise argparse.ArgumentTypeError("cap must be PATH=LINES")
    try:
        cap = int(raw_cap)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("cap line count must be an integer") from exc
    if cap <= 0:
        raise argparse.ArgumentTypeError("cap line count must be positive")
    return relative, cap


def check_format(root: Path, sources: list[Path]) -> int:
    formatter = shutil.which("clang-format")
    if formatter is None:
        print("cpp-policy: REFUSED — clang-format is not installed", file=sys.stderr)
        return 2
    if not sources:
        print("cpp-policy: format-checked 0 first-party files (declared scaffold)")
        return 0
    formatted = subprocess.run(
        [formatter, "--dry-run", "--Werror", *map(str, sources)],
        cwd=root,
        check=False,
    )
    print(f"cpp-policy: format-checked {len(sources)} first-party file(s)")
    if formatted.returncode:
        print("cpp-policy: FAIL — run clang-format with the repository .clang-format", file=sys.stderr)
        return 1
    return 0


def check_caps(root: Path, sources: list[Path], caps: dict[str, int]) -> int:
    known = {str(path.relative_to(root)) for path in sources}
    missing = sorted(relative for relative in caps if relative not in known)
    if missing:
        print(f"cpp-policy: REFUSED — capped file(s) missing or excluded: {', '.join(missing)}", file=sys.stderr)
        return 2

    failed = False
    critical = 0
    for path in sources:
        relative = str(path.relative_to(root))
        lines = len(path.read_text(encoding="utf-8", errors="replace").splitlines())
        cap = caps.get(relative, DEFAULT_CAP)
        if relative in caps or lines > DEFAULT_CAP:
            label = "critical legacy" if lines >= CRITICAL_LINES else "legacy"
            print(f"cpp-policy: {relative}: {lines}/{cap} lines ({label})")
        if lines > cap:
            print(
                f"cpp-policy: FAIL — {relative} has {lines} lines, above its {cap}-line cap; "
                "extract a cohesive owner",
                file=sys.stderr,
            )
            failed = True
        if lines >= CRITICAL_LINES:
            critical += 1
    print(
        f"cpp-policy: size-checked {len(sources)} file(s) at {DEFAULT_CAP} default; "
        f"{len(caps)} explicit cap(s), {critical} critical legacy file(s)"
    )
    return 1 if failed else 0


def touched_cpp_tus(root: Path) -> list[str]:
    changed = set(
        run_git(
            root,
            "diff",
            "--name-only",
            "--diff-filter=ACMR",
            "HEAD",
            "--",
            "*.cc",
            "*.cpp",
            "*.cxx",
        )
    )
    changed.update(
        run_git(
            root,
            "ls-files",
            "--others",
            "--exclude-standard",
            "--",
            "*.cc",
            "*.cpp",
            "*.cxx",
        )
    )
    return sorted(
        relative
        for relative in changed
        if Path(relative).parts
        and Path(relative).parts[0] not in EXCLUDED_TOP_LEVEL
        and not is_generated(root / relative)
    )


def compile_file(entry: dict[str, object]) -> Path:
    path = Path(str(entry["file"]))
    if not path.is_absolute():
        path = Path(str(entry["directory"])) / path
    return path.resolve()


def command_uses_clang(entry: dict[str, object]) -> bool:
    if isinstance(entry.get("arguments"), list):
        words = [str(word) for word in entry["arguments"]]
    else:
        words = shlex.split(str(entry.get("command", "")))
    wrappers = {"ccache", "distcc", "env", "sccache"}
    for word in words:
        base = Path(word).name
        if base in wrappers or ("=" in word and not word.startswith("-")):
            continue
        return base == "clang-cl" or base.startswith("clang++")
    return False


def check_tidy(root: Path, compile_commands: Path, sources: list[Path], touched_only: bool) -> int:
    tidy = shutil.which("clang-tidy")
    if tidy is None:
        print("cpp-policy: REFUSED — clang-tidy is not installed", file=sys.stderr)
        return 2
    config = root / ".clang-tidy"
    if not config.is_file():
        print("cpp-policy: REFUSED — tracked .clang-tidy is missing", file=sys.stderr)
        return 2

    database_file = compile_commands / "compile_commands.json" if compile_commands.is_dir() else compile_commands
    if not database_file.is_file():
        print(f"cpp-policy: REFUSED — compile database missing: {database_file}", file=sys.stderr)
        return 2
    try:
        database = json.loads(database_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"cpp-policy: REFUSED — cannot read {database_file}: {exc}", file=sys.stderr)
        return 2

    touched = set(touched_cpp_tus(root))
    if touched_only and not touched:
        print("cpp-policy: clang-tidy checked 0 touched C++ translation units (none touched)")
        return 0
    candidates = (
        sorted(touched)
        if touched_only
        else [str(path.relative_to(root)) for path in sources if path.suffix in {".cc", ".cpp", ".cxx"}]
    )
    if not candidates:
        print("cpp-policy: clang-tidy checked 0 of 0 C++ TUs (declared source-free scaffold)")
        return 0

    by_file: dict[Path, list[dict[str, object]]] = {}
    for raw_entry in database:
        if isinstance(raw_entry, dict) and "file" in raw_entry and "directory" in raw_entry:
            entry = raw_entry
            by_file.setdefault(compile_file(entry), []).append(entry)

    missing: list[str] = []
    non_clang: list[str] = []
    paths: list[Path] = []
    for relative in candidates:
        path = (root / relative).resolve()
        entries = by_file.get(path, [])
        if not entries:
            missing.append(relative)
            continue
        if not all(command_uses_clang(entry) for entry in entries):
            non_clang.append(relative)
            continue
        paths.append(path)
    required_missing = missing if touched_only else sorted(set(missing) & touched)
    if required_missing:
        print(
            "cpp-policy: REFUSED — touched C++ TU(s) absent from compile_commands.json: "
            f"{', '.join(required_missing)}",
            file=sys.stderr,
        )
        return 2
    if non_clang:
        print(
            f"cpp-policy: REFUSED — touched C++ TU(s) were not compiled with clang++: {', '.join(non_clang)}",
            file=sys.stderr,
        )
        return 2

    if not paths:
        print("cpp-policy: REFUSED — compile database covers no first-party C++ translation units", file=sys.stderr)
        return 2

    line_filter = json.dumps(
        [
            {
                "name": str(path),
                "lines": [[1, max(1, len(path.read_text(encoding="utf-8", errors="replace").splitlines()))]],
            }
            for path in paths
        ],
        separators=(",", ":"),
    )
    runner = shutil.which("run-clang-tidy")
    if runner:
        jobs = min(8, os.cpu_count() or 1)
        command = [
            runner,
            "-quiet",
            "-hide-progress",
            "-j",
            str(jobs),
            "-clang-tidy-binary",
            tidy,
            "-config-file",
            str(config),
            "-line-filter",
            line_filter,
            "-p",
            str(database_file.parent),
            *[f"^{re.escape(str(path))}$" for path in paths],
        ]
    else:
        command = [
            tidy,
            "--quiet",
            f"--config-file={config}",
            f"--line-filter={line_filter}",
            "-p",
            str(database_file.parent),
            *map(str, paths),
        ]
    result = subprocess.run(command, cwd=root, check=False)
    scope = "touched" if touched_only else "first-party"
    print(
        f"cpp-policy: clang-tidy checked {len(paths)} of {len(candidates)} {scope} C++ TU(s) "
        f"with compile commands; {len(missing)} not compile-backed"
    )
    if missing:
        print(f"cpp-policy: not compile-backed (not linted): {', '.join(missing)}")
    return 1 if result.returncode else 0


def selftest_write_database(root: Path, compiler: str = "clang++", include_source: bool = True) -> None:
    build = root / "build"
    build.mkdir(exist_ok=True)
    entries = []
    if include_source:
        entries.append(
            {
                "directory": str(build),
                "command": f"{compiler} -std=c++20 -c {root / 'a.cpp'} -o a.o",
                "file": str(root / "a.cpp"),
            }
        )
    (build / "compile_commands.json").write_text(json.dumps(entries), encoding="utf-8")


def selftest_run(root: Path, *extra: str) -> tuple[int, str]:
    result = subprocess.run(
        [
            sys.executable,
            str(Path(__file__).resolve()),
            "--root",
            str(root),
            "--compile-commands",
            str(root / "build"),
            *extra,
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    return result.returncode, result.stdout + result.stderr


def selftest() -> int:
    scratch = SCRIPT_ROOT / "scratch"
    scratch.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="cpp-policy-selftest-", dir=scratch) as temp:
        root = Path(temp)
        (root / ".clang-format").write_text(
            (SCRIPT_ROOT / ".clang-format").read_text(encoding="utf-8"),
            encoding="utf-8",
        )
        tidy_text = (SCRIPT_ROOT / ".clang-tidy").read_text(encoding="utf-8")
        (root / ".clang-tidy").write_text(tidy_text, encoding="utf-8")
        source_text = "int main() {\n  return 0;\n}\n"
        (root / "a.cpp").write_text(source_text, encoding="utf-8")
        (root / "deleted.cpp").write_text(source_text, encoding="utf-8")
        subprocess.run(["git", "init", "-q", str(root)], check=True)
        subprocess.run(["git", "-C", str(root), "add", "."], check=True)
        subprocess.run(
            [
                "git",
                "-C",
                str(root),
                "-c",
                "user.name=cpp-policy-selftest",
                "-c",
                "user.email=selftest@example.invalid",
                "-c",
                "commit.gpgsign=false",
                "commit",
                "-qm",
                "fixture",
            ],
            check=True,
        )
        (root / "deleted.cpp").unlink()
        selftest_write_database(root)

        def expect(name: str, want_code: int, needle: str, *extra: str) -> None:
            code, output = selftest_run(root, *extra)
            if code != want_code or needle not in output:
                raise RuntimeError(
                    f"{name}: expected rc={want_code} and {needle!r}; got rc={code}\n{output}"
                )
            print(f"cpp-policy selftest: PASS {name}")

        expect("happy clean tree lints one TU", 0, "checked 1 of 1 first-party C++ TU")
        expect("tracked deletion is excluded", 0, "1 worktree-deleted file(s)")

        (root / ".clang-tidy").unlink()
        expect("missing clang-tidy config refuses", 2, "tracked .clang-tidy is missing")
        (root / ".clang-tidy").write_text(tidy_text, encoding="utf-8")

        expect(
            "missing compile database refuses",
            2,
            "compile database missing",
            "--compile-commands",
            str(root / "absent-build"),
        )

        selftest_write_database(root, compiler="g++")
        expect("non-Clang compile command refuses", 2, "were not compiled with clang++")

        selftest_write_database(root, include_source=False)
        (root / "a.cpp").write_text(source_text + "// touched\n", encoding="utf-8")
        expect(
            "touched TU missing from database refuses",
            2,
            "absent from compile_commands.json",
            "--tidy-touched",
        )

        (root / "a.cpp").write_text(source_text, encoding="utf-8")
        selftest_write_database(root)
        expect("explicit size cap fails", 1, "above its 1-line cap", "--cap", "a.cpp=1")

        (root / "a.cpp").write_text("int main(){return 0;}\n", encoding="utf-8")
        expect("format drift fails", 1, "run clang-format")

    print("cpp-policy selftest: 8/8 cases passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--selftest", action="store_true", help="exercise success and every refusal/failure class")
    parser.add_argument("--root", type=Path, default=SCRIPT_ROOT, help="repository root (default: psxport)")
    parser.add_argument(
        "--compile-commands",
        type=Path,
        help="compile_commands.json or its directory (default: ROOT/build)",
    )
    parser.add_argument(
        "--cap",
        action="append",
        default=[],
        type=parse_cap,
        metavar="PATH=LINES",
        help="explicit shrink-only cap for a legacy or deliberately smaller file",
    )
    parser.add_argument(
        "--allow-empty-scaffold",
        action="store_true",
        help="accept an explicitly source-free consumer scaffold while still checking its policy files/tools",
    )
    parser.add_argument(
        "--tidy-touched",
        action="store_true",
        help="fast local mode: lint only worktree-touched C++ TUs (normal CTest must omit this)",
    )
    args = parser.parse_args()

    if args.selftest:
        return selftest()

    root = args.root.resolve()
    if not (root / ".git").exists():
        print(f"cpp-policy: REFUSED — not a repository root: {root}", file=sys.stderr)
        return 2
    if not (root / ".clang-format").is_file():
        print("cpp-policy: REFUSED — tracked .clang-format is missing", file=sys.stderr)
        return 2

    sources, generated, deleted = source_files(root)
    if not sources and not args.allow_empty_scaffold:
        print("cpp-policy: REFUSED — no tracked first-party C/C++ files were found", file=sys.stderr)
        return 2
    if not sources and root == SCRIPT_ROOT:
        print("cpp-policy: REFUSED — psxport itself cannot be an empty consumer scaffold", file=sys.stderr)
        return 2
    print(
        "cpp-policy: excluded vendor/generated trees, "
        f"{len(generated)} generated file(s), and {len(deleted)} worktree-deleted file(s)"
    )

    caps = dict(PSXPORT_CAPS) if root == SCRIPT_ROOT else {}
    caps.update(dict(args.cap))
    compile_commands = (args.compile_commands or (root / "build")).resolve()

    result = check_format(root, sources)
    if result:
        return result
    result = check_caps(root, sources, caps)
    if result:
        return result
    result = check_tidy(root, compile_commands, sources, args.tidy_touched)
    if result:
        return result
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
