#!/usr/bin/env python3
# findings.py — the project's SEARCHABLE FINDINGS REGISTRY.
#
# WHY THIS EXISTS: docs/journal.md is an 8000+-line append-only chronological log — findings pile up
# there and become unfindable, so each session re-derives solved problems. This registry is the
# OPPOSITE: findings live in docs/findings/<subsystem>.md as small tagged blocks keyed by SYMPTOM (the
# words you'd grep when you hit the bug again), and this tool greps them + regenerates a compact INDEX.
#
# THE LOOP (do this, every session):
#   tools/findings.py <words>     # BEFORE investigating any bug: "have we already solved/ruled this out?"
#   ... fix it ...
#   # append a block to docs/findings/<subsystem>.md (format below), then:
#   tools/findings.py             # regenerate docs/findings/INDEX.md (read it at session start)
#
# FINDING BLOCK FORMAT (in docs/findings/<subsystem>.md) — one `## ` per finding:
#   ## <short title>
#   - **symptom:** how it presents — the literal words you'd grep (error text, visible glitch)
#   - **status:** fixed <commit> | known-issue | dead-end | wontfix
#   - **cause:** root cause in a line or two
#   - **fix:** what was done, OR what NOT to retry (for dead-ends)
#   - **refs:** journal later-NNN, file.cpp:line, commit hash
import os, re, sys, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FDIR = os.path.join(ROOT, "docs", "findings")
FIELDS = ("symptom", "status", "cause", "fix", "refs")

def parse(path):
    """Yield (title, {field: text}) blocks from a findings file."""
    with open(path) as f:
        text = f.read()
    blocks = re.split(r"(?m)^## +", text)
    for b in blocks[1:]:
        lines = b.splitlines()
        title = lines[0].strip()
        fields = {}
        for k in FIELDS:
            m = re.search(r"(?im)^\s*[-*]?\s*\*\*%s:\*\*\s*(.+?)\s*$" % k, b)
            if m:
                fields[k] = m.group(1).strip()
        yield title, fields

def all_findings():
    for path in sorted(glob.glob(os.path.join(FDIR, "*.md"))):
        sub = os.path.splitext(os.path.basename(path))[0]
        if sub == "INDEX":
            continue
        for title, fields in parse(path):
            yield sub, title, fields

def gen_index():
    rows = list(all_findings())
    out = ["# Findings index — AUTO-GENERATED by tools/findings.py (do not hand-edit).",
           "",
           "Grep this (or `tools/findings.py <words>`) BEFORE investigating a bug — to find whether it's",
           f"already solved or ruled out. {len(rows)} findings across "
           f"{len(set(r[0] for r in rows))} subsystems.",
           ""]
    cur = None
    for sub, title, f in sorted(rows):
        if sub != cur:
            out += ["", f"## {sub}", ""]
            cur = sub
        st = f.get("status", "?")
        sym = f.get("symptom", "")
        out.append(f"- **{title}** [{st}] — {sym}  ↪ docs/findings/{sub}.md")
    with open(os.path.join(FDIR, "INDEX.md"), "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"[findings] wrote docs/findings/INDEX.md ({len(rows)} findings)")

def search_journal(terms):
    """Raw search of docs/journal.md `## ` entries — the un-promoted history. Returns (title, snippet)."""
    jpath = os.path.join(ROOT, "docs", "journal.md")
    if not os.path.exists(jpath):
        return
    with open(jpath) as f:
        text = f.read()
    for b in re.split(r"(?m)^## +", text)[1:]:
        title = b.splitlines()[0].strip()
        low = b.lower()
        if all(t in low for t in terms):
            # one-line snippet: the first non-blank line after the title
            snip = next((l.strip() for l in b.splitlines()[1:] if l.strip()), "")
            yield title, snip[:200]

def query(words):
    terms = [w.lower() for w in words]
    hits = 0
    for sub, title, f in all_findings():
        hay = " ".join([title] + list(f.values())).lower()
        if all(t in hay for t in terms):
            hits += 1
            print(f"\n## [{sub}] {title}  ({f.get('status','?')})")
            for k in FIELDS:
                if k in f:
                    print(f"  {k:8}: {f[k]}")
    # Also search the raw journal (un-promoted history) so NOTHING is unfindable. Curated registry
    # findings above are authoritative; journal hits are raw leads — promote one to docs/findings/ if
    # it's still relevant and you had to dig for it.
    jhits = list(search_journal(terms))
    if jhits:
        print(f"\n--- {len(jhits)} raw journal hit(s) (docs/journal.md — promote to a finding if useful) ---")
        for title, snip in jhits:
            print(f"  journal ## {title}\n      {snip}")
    if not hits and not jhits:
        print(f"[findings] no match for {words!r} in the registry OR the journal — likely NOT yet "
              "investigated. Solve it, then add a block to docs/findings/<subsystem>.md.")

def main():
    os.makedirs(FDIR, exist_ok=True)
    if len(sys.argv) > 1:
        query(sys.argv[1:])
    else:
        gen_index()

if __name__ == "__main__":
    main()
