#!/usr/bin/env bash
# Compile the SDL_GPU shaders (runtime/recomp/shaders_gpu/*.{vert,frag}) to SPIR-V and embed them as
# uint32_t arrays in a generated header (runtime/recomp/gpu_gpu_shaders.h), so gpu_gpu.cpp has no runtime
# file dependency. SDL_GPU's Vulkan backend consumes SPIR-V directly (SDL_CreateGPUShader with
# SDL_GPU_SHADERFORMAT_SPIRV); the GLSL uses SDL_GPU's binding convention (fragment samplers set=2,
# fragment uniform buffers set=3). For Metal (Mac), transpile this SPIR-V via SDL_shadercross (later).
# Called by run.sh / tools/build_port.sh before compiling gpu_gpu.cpp. Idempotent. Requires glslc.
set -eu
cd "$(dirname "$0")/.."
SH=runtime/recomp/shaders_gpu
OUT=runtime/recomp/gpu_gpu_shaders.h
command -v glslc >/dev/null || { echo "gen_gpu_shaders: glslc not found (install the Vulkan SDK)" >&2; exit 1; }

newest=$(ls -t "$SH"/*.vert "$SH"/*.frag tools/gen_gpu_shaders.sh 2>/dev/null | head -1)
[ -f "$OUT" ] && [ "$OUT" -nt "$newest" ] && exit 0

tmp="$(mktemp -d)"
emit() {  # $1 = source, $2 = C array name
  glslc "$SH/$1" -o "$tmp/$1.spv"
  python3 - "$tmp/$1.spv" "$2" <<'PY'
import sys, struct
data = open(sys.argv[1], 'rb').read()
assert len(data) % 4 == 0, "SPIR-V not word-aligned"
words = struct.unpack('<%dI' % (len(data)//4), data)
print("static const uint32_t %s[] = {" % sys.argv[2])
for i in range(0, len(words), 8):
    print("  " + ", ".join("0x%08x" % w for w in words[i:i+8]) + ",")
print("};")
print("static const unsigned %s_len = sizeof(%s);" % (sys.argv[2], sys.argv[2]))
PY
}
{
  echo "// GENERATED by tools/gen_gpu_shaders.sh — do not edit. SPIR-V for the SDL_GPU renderer (gpu_gpu.cpp)."
  echo "#include <stdint.h>"
  emit present.vert spv_g_present_vert
  emit present.frag spv_g_present_frag
  emit image.vert   spv_g_image_vert
  emit image.frag   spv_g_image_frag
  emit tri.vert     spv_g_tri_vert      # Pass 2: native 3D raster (untextured opaque)
  emit tri.frag     spv_g_tri_frag
  emit tritex.vert  spv_g_tritex_vert   # native 3D raster (textured, opaque + semi-source sampling)
  emit tritex.frag  spv_g_tritex_frag
  emit rml.vert     spv_g_rml_vert      # RmlUi 2D mod/debug overlay (textured + premult-alpha blend)
  emit rml.frag     spv_g_rml_frag
  emit fsq.vert       spv_g_fsq_vert        # semi real-HW-blend intermediate: shared fullscreen-tri vert
  emit decode.frag    spv_g_decode_frag     # 1555 VRAM -> float RGBA (before the semi pass)
  emit encode.frag    spv_g_encode_frag     # float RGBA -> 1555 VRAM (after the semi pass)
  emit trisemi_hw.frag spv_g_trisemi_hw_frag # real HW-blend textured semi (reuses tritex.vert)
} > "$OUT"
echo "[gen_gpu_shaders] wrote $OUT"
