#!/usr/bin/env bash
# Compile the Vulkan shaders (runtime/recomp/shaders_vk/*.{vert,frag}) to SPIR-V and embed them as
# uint32_t arrays in a generated header (runtime/recomp/gpu_vk_shaders.h), so gpu_vk.c has no runtime
# file dependency. Called by run.sh / tools/build_port.sh before compiling gpu_vk.c. Idempotent;
# regenerates only when a shader is newer than the header. Requires glslc (Vulkan SDK).
set -eu
cd "$(dirname "$0")/.."
SH=runtime/recomp/shaders_vk
OUT=runtime/recomp/gpu_vk_shaders.h
command -v glslc >/dev/null || { echo "gen_vk_shaders: glslc not found (install the Vulkan SDK)" >&2; exit 1; }

# up-to-date check
newest=$(ls -t "$SH"/*.vert "$SH"/*.frag tools/gen_vk_shaders.sh 2>/dev/null | head -1)
[ -f "$OUT" ] && [ "$OUT" -nt "$newest" ] && exit 0

tmp="$(mktemp -d)"
emit() {  # $1 = source, $2 = C array name
  glslc "$SH/$1" -o "$tmp/$1.spv"
  python3 - "$tmp/$1.spv" "$2" <<'PY'
import sys, struct
data = open(sys.argv[1], 'rb').read()
assert len(data) % 4 == 0, "SPIR-V not word-aligned"
words = struct.unpack('<%dI' % (len(data)//4), data)
print("static const uint32_t %s[] = {" % sys.argv[2])
for i in range(0, len(words), 8):
    print("  " + ", ".join("0x%08x" % w for w in words[i:i+8]) + ",")
print("};")
print("static const unsigned %s_len = sizeof(%s);" % (sys.argv[2], sys.argv[2]))
PY
}
{
  echo "// GENERATED by tools/gen_vk_shaders.sh — do not edit. SPIR-V for gpu_vk.c present pass."
  echo "#include <stdint.h>"
  emit present.vert spv_present_vert
  emit present.frag spv_present_frag
  emit tri.vert spv_tri_vert
  emit tri.frag spv_tri_frag
} > "$OUT"
echo "[gen_vk_shaders] wrote $OUT"
