// gte_state.h — per-instance GTE (COP2) register state, so two Cores run with SEPARATE GTE state
// (user 2026-06-24: "make all states OOP and feed two cores separate states — we are in charge, not
// Beetle"). The Beetle GTE math (mednafen/psx/gte.c) used a file-scope REG[64]+FLAGS; that mutable
// state now lives in this struct, one per Game (game.h embeds it). gte.c is BOUND to one instance at a
// time via GTE_BindState — set from the explicit Core before that core runs (gte_beetle.cpp gte_bind),
// so each core reads/writes only its own registers; nothing is shared (DivTable stays a const table).
#pragma once
#include <stdint.h>

// GTE diagnostics (gte_beetle.cpp probes) — per-instance so two SBS cores keep separate histograms.
// Plain-C so GteRegs stays a C struct. All fields are pure diagnostics (env/`debug`-gated).
typedef struct GteDebug {
  long sx_hist[16];                      // PSXPORT_WS_SXHIST screen-X histogram (was s_sx_hist)
  long sx_n, sx_oob_lo, sx_oob_hi;
  int  sxhist_on;                        // -1 = not read yet
  long gte_hist[64];                     // PSXPORT_GTEPROBE executed-op histogram (was s_gte_hist)
  int  gteprobe, gteprobe_done;          // gteprobe: -1 = not read yet
  int  projprobe;                        // PSXPORT_PROJPROBE (-1 = not read yet)
  long pp_verts, pp_bad_ir, pp_bad_sz, pp_bad_sx, pp_bad_sy;
  int  pp_maxd_ir, pp_maxd_sz, pp_maxd_sx, pp_maxd_sy;
  long pp_subpix_le1;
  struct { uint32_t ra; long n; } rtpcaller[64];   // PSXPORT_RTPCALLER RA histogram
  int  rtpcaller_on;                     // -1 = not read yet
} GteDebug;

typedef struct GteRegs {
  uint32_t REG[64];     // DR = REG[0..31] (data regs), CR = REG[32..63] (control regs)
  uint32_t FLAGS;       // overflow flags generated by GTE commands
  uint32_t *CR, *DR;    // point into REG (REG+32 / REG); (re)set by GTE_BindState
  GteDebug dbg;         // per-instance probe/histogram state (gte_beetle.cpp)
} GteRegs;

#ifdef __cplusplus
extern "C" {
#endif
// Make `s` the active GTE instance for all subsequent GTE_* calls; lazily inits its CR/DR pointers.
void     GTE_BindState(GteRegs* s);
GteRegs* GTE_CurState(void);
#ifdef __cplusplus
}
#endif
