// gte_state.h — per-instance GTE (COP2) register state, so two Cores run with SEPARATE GTE state
// (user 2026-06-24: "make all states OOP and feed two cores separate states — we are in charge, not
// Beetle"). The Beetle GTE math (mednafen/psx/gte.c) used a file-scope REG[64]+FLAGS; that mutable
// state now lives in this struct, one per Game (game.h embeds it). gte.c is BOUND to one instance at a
// time via GTE_BindState — set from the explicit Core before that core runs (gte_beetle.cpp gte_bind),
// so each core reads/writes only its own registers; nothing is shared (DivTable stays a const table).
#pragma once
#include <stdint.h>

typedef struct GteRegs {
  uint32_t REG[64];     // DR = REG[0..31] (data regs), CR = REG[32..63] (control regs)
  uint32_t FLAGS;       // overflow flags generated by GTE commands
  uint32_t *CR, *DR;    // point into REG (REG+32 / REG); (re)set by GTE_BindState
} GteRegs;

#ifdef __cplusplus
extern "C" {
#endif
// Make `s` the active GTE instance for all subsequent GTE_* calls; lazily inits its CR/DR pointers.
void     GTE_BindState(GteRegs* s);
GteRegs* GTE_CurState(void);
#ifdef __cplusplus
}
#endif
